package util;

public enum TokenType {
	IDENTIFIER, NUMBER, REL_OPERATOR, MATH_OPERATOR, ASSIGNMENT, L_PAREN, R_PAREN, INT, FLOAT, INICIO, DECLS, FIMDECLS, CODIGO, FIMPROG, LEIA, ESCREVA, E, OU, SE, ENTAO, SENAO, REPITA, BLOCO, FIMBLOCO, CADEIA, COLON;
}
